@@include('files/dynamic_adapt.js', {})
@@include('libs/swiper.min.js', {})
@@include('libs/tippy.js', {})
@@include('libs/BeerSlider.unmin.js', {})
@@include('./tabs.js', {})
@@include('../../node_modules/body-scroll-lock/lib/bodyScrollLock.min.js', {})
